// packages/mobile/src/design/iconMap.ts
//
// Curated map from the spec's Material Symbols vocabulary to the glyphs available in
// `@expo/vector-icons` (MaterialIcons primary, Ionicons fallback). Keeping this in one place
// means screens reference semantic names (`menu`, `home`, `report_problem`) and the mapping
// to a concrete library lives here only.
//
// Extend this map as new screens need new icons — prefer MaterialIcons glyph names that
// match the Material Symbols name verbatim; otherwise note the divergence in a comment.

export type IconSetName = "material" | "ionicons";

export interface ResolvedIcon {
  set: IconSetName;
  glyph: string;
}

export const iconSet: Record<string, ResolvedIcon> = {
  // Navigation / chrome
  menu: { set: "material", glyph: "menu" },
  close: { set: "material", glyph: "close" },
  arrow_back: { set: "material", glyph: "arrow-back" },
  arrow_forward: { set: "material", glyph: "arrow-forward" },
  chevron_right: { set: "material", glyph: "chevron-right" },
  chevron_left: { set: "material", glyph: "chevron-left" },
  more_horiz: { set: "material", glyph: "more-horiz" },
  more_vert: { set: "material", glyph: "more-vert" },
  search: { set: "material", glyph: "search" },
  filter_list: { set: "material", glyph: "filter-list" },
  add: { set: "material", glyph: "add" },
  remove: { set: "material", glyph: "remove" },
  check: { set: "material", glyph: "check" },
  check_circle: { set: "material", glyph: "check-circle" },
  circle: { set: "material", glyph: "circle" },
  radio_button_checked: { set: "material", glyph: "radio-button-checked" },
  radio_button_unchecked: { set: "material", glyph: "radio-button-unchecked" },
  error: { set: "material", glyph: "error" },
  warning: { set: "material", glyph: "warning" },
  info: { set: "material", glyph: "info" },
  help: { set: "material", glyph: "help" },
  refresh: { set: "material", glyph: "refresh" },
  sync: { set: "material", glyph: "sync" },
  edit: { set: "material", glyph: "edit" },
  delete: { set: "material", glyph: "delete" },
  upload_file: { set: "material", glyph: "upload-file" },
  download: { set: "material", glyph: "download" },
  visibility: { set: "material", glyph: "visibility" },
  visibility_off: { set: "material", glyph: "visibility-off" },
  settings: { set: "material", glyph: "settings" },
  logout: { set: "material", glyph: "logout" },
  login: { set: "material", glyph: "login" },
  fingerprint: { set: "material", glyph: "fingerprint" },
  shield_person: { set: "material", glyph: "shield" },
  gpp_good: { set: "material", glyph: "gpp-good" },
  verified_user: { set: "material", glyph: "verified-user" },
  lock: { set: "material", glyph: "lock" },
  qr_code_scanner: { set: "material", glyph: "qr-code-scanner" },

  // Bottom nav / home
  home: { set: "material", glyph: "home" },
  local_gas_station: { set: "material", glyph: "local-gas-station" },
  fact_check: { set: "material", glyph: "fact-check" },
  report_problem: { set: "material", glyph: "report-problem" },
  support_agent: { set: "material", glyph: "support-agent" },
  dashboard: { set: "material", glyph: "dashboard" },
  directions_car: { set: "material", glyph: "directions-car" },
  group: { set: "material", glyph: "group" },
  build: { set: "material", glyph: "build" },
  person: { set: "material", glyph: "person" },
  notifications: { set: "material", glyph: "notifications" },
  notifications_none: { set: "material", glyph: "notifications-none" },
  location_on: { set: "material", glyph: "location-on" },
  my_location: { set: "material", glyph: "my-location" },
  place: { set: "material", glyph: "place" },
  map: { set: "material", glyph: "map" },
  layers: { set: "material", glyph: "layers" },
  route: { set: "material", glyph: "route" },
  pin_drop: { set: "material", glyph: "pin-drop" },
  swap_horiz: { set: "material", glyph: "swap-horiz" },
  swap_vert: { set: "material", glyph: "swap-vert" },
  trailer_swap: { set: "material", glyph: "swap-horiz" },
  rv_hookup: { set: "material", glyph: "rv-hookup" },
  local_shipping: { set: "material", glyph: "local-shipping" },
  schedule: { set: "material", glyph: "schedule" },
  timer: { set: "material", glyph: "timer" },
  power_settings_new: { set: "material", glyph: "power-settings-new" },
  play_circle: { set: "material", glyph: "play-circle" },
  menu_book: { set: "material", glyph: "menu-book" },
  school: { set: "material", glyph: "school" },
  card_membership: { set: "material", glyph: "card-membership" },
  badge: { set: "material", glyph: "badge" },
  medical_services: { set: "material", glyph: "medical-services" },
  call: { set: "material", glyph: "call" },
  mail: { set: "material", glyph: "mail" },
  home_pin: { set: "material", glyph: "home-pin" },
  id_card: { set: "material", glyph: "id-card" },
  camera: { set: "material", glyph: "camera" },
  photo_camera: { set: "material", glyph: "photo-camera" },
  add_a_photo: { set: "material", glyph: "add-a-photo" },
  image: { set: "material", glyph: "image" },
  videocam: { set: "material", glyph: "videocam" },
  attach_file: { set: "material", glyph: "attach-file" },
  zoom_in: { set: "material", glyph: "zoom-in" },
  rotate_right: { set: "material", glyph: "rotate-right" },
  description: { set: "material", glyph: "description" },
  receipt_long: { set: "material", glyph: "receipt-long" },
  credit_card: { set: "material", glyph: "credit-card" },
  gas_meter: { set: "material", glyph: "gas-meter" },
  speed: { set: "material", glyph: "speed" },
  oil_barrel: { set: "material", glyph: "oil-barrel" },
  water_drop: { set: "material", glyph: "water-drop" },
  tire_repair: { set: "material", glyph: "tire-repair" },
  thermostat: { set: "material", glyph: "thermostat" },
  ev_station: { set: "material", glyph: "ev-station" },
  battery_charging_full: { set: "material", glyph: "battery-charging-full" },
  bolt: { set: "material", glyph: "bolt" },
  gavel: { set: "material", glyph: "gavel" },
  warning_amber: { set: "material", glyph: "warning-amber" },
  error_outline: { set: "material", glyph: "error-outline" },
  bar_chart: { set: "material", glyph: "bar-chart" },
  notifications_active: { set: "material", glyph: "notifications-active" },
  insights: { set: "material", glyph: "insights" },
  rule: { set: "material", glyph: "rule" },
  people: { set: "material", glyph: "people" },
  campaign: { set: "material", glyph: "campaign" },
  check_circle_outline: { set: "material", glyph: "check-circle-outline" },
  pending: { set: "material", glyph: "pending" },
  pending_actions: { set: "material", glyph: "pending-actions" },
  assignment: { set: "material", glyph: "assignment" },
  assignment_late: { set: "material", glyph: "assignment-late" },
  assignment_turned_in: { set: "material", glyph: "assignment-turned-in" },
  calendar_today: { set: "material", glyph: "calendar-today" },
  history: { set: "material", glyph: "history" },
  list: { set: "material", glyph: "list" },
  grid_view: { set: "material", glyph: "grid-view" },
  view_list: { set: "material", glyph: "view-list" },
  expand_more: { set: "material", glyph: "expand-more" },
  expand_less: { set: "material", glyph: "expand-less" },
  keyboard_arrow_down: { set: "material", glyph: "keyboard-arrow-down" },
  navigate_next: { set: "material", glyph: "navigate-next" },
  navigate_before: { set: "material", glyph: "navigate-before" },
  first_page: { set: "material", glyph: "first-page" },
  last_page: { set: "material", glyph: "last-page" },
  language: { set: "material", glyph: "language" },
  dark_mode: { set: "material", glyph: "dark-mode" },
  light_mode: { set: "material", glyph: "light-mode" },
  wifi: { set: "material", glyph: "wifi" },
  wifi_off: { set: "material", glyph: "wifi-off" },
  cloud_off: { set: "material", glyph: "cloud-off" },
  cloud_done: { set: "material", glyph: "cloud-done" },
  cloud_upload: { set: "material", glyph: "cloud-upload" },
  send: { set: "material", glyph: "send" },
  message: { set: "material", glyph: "message" },
  chat: { set: "material", glyph: "chat" },
  phone: { set: "material", glyph: "phone" },
  contact_support: { set: "material", glyph: "contact-support" },
  help_outline: { set: "material", glyph: "help-outline" },
  info_outline: { set: "material", glyph: "info-outline" },
  star: { set: "material", glyph: "star" },
  bookmark: { set: "material", glyph: "bookmark" },
  flag: { set: "material", glyph: "flag" },
  bookmark_add: { set: "material", glyph: "bookmark-add" },
  add_circle: { set: "material", glyph: "add-circle" },
  add_circle_outline: { set: "material", glyph: "add-circle-outline" },
  remove_circle: { set: "material", glyph: "remove-circle" },
  restore: { set: "material", glyph: "restore" },
  restart_alt: { set: "material", glyph: "restart-alt" },
  content_copy: { set: "material", glyph: "content-copy" },
  print: { set: "material", glyph: "print" },
  download_for_offline: { set: "material", glyph: "download-for-offline" },
  hub: { set: "material", glyph: "hub" },
  medical_information: { set: "material", glyph: "medical-information" },
  document_scanner: { set: "material", glyph: "document-scanner" },
  inventory_2: { set: "material", glyph: "inventory-2" },
  category: { set: "material", glyph: "category" },
  label: { set: "material", glyph: "label" },
  visibility_lock: { set: "material", glyph: "visibility-lock" },

  // Filled variants (Material Symbols FILL=1) — only meaningful where the lib supports it.
  "home.filled": { set: "material", glyph: "home-filled" } as any,
  "dashboard.filled": { set: "material", glyph: "dashboard" },
  "notifications.filled": { set: "material", glyph: "notifications" },
  "local_gas_station.filled": { set: "material", glyph: "local-gas-station" },
  "fact_check.filled": { set: "material", glyph: "fact-check" },
  "report_problem.filled": { set: "material", glyph: "report-problem" },
  "person.filled": { set: "material", glyph: "person" },
  "check_circle.filled": { set: "material", glyph: "check-circle" },
};

/** Resolve a (name, filled) pair to a stable map key. */
export function iconKey(name: string, filled: boolean): string {
  return filled ? `${name}.filled` : name;
}
